Train:
  batch_size: 64
  learning_rate: 1
  reg: 0.000000000000000001
  epochs: 11
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet


