Train:
  batch_size: 128
  learning_rate: 0.01
  reg: 0.001
  epochs: 5
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32
  save_best: True

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.77

loss:
  loss_type: Focal # CE or Focal
